services:

  pma:
    image: phpmyadmin:5.2.0-apache
    platform: linux/amd64
    hostname: pma
    ports:
      - "127.0.0.1:9981:80"
    networks:
      - backend
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=10M
    restart: always
    depends_on:
      - db
    
  webserver:
    image: statea/webserver
    platform: linux/amd64
    build: ./webserver/
    hostname: webserver
    ports:
      - "9980:8080"
    networks:
      - frontend
      - backend
    environment:
      - TZ=Europe/Rome
    restart: always
    depends_on:
      - db

  frontend:
    image: statea/frontend
    platform: linux/amd64
    build: ./frontend/
    hostname: frontend
    ports:
      - "9930:9930"
    networks:
      - frontend
    restart: always
    depends_on:
      - webserver

  consumerstats:
    image: statea/consumerstats
    platform: linux/amd64
    build: ./consumerstats/
    hostname: consumerstats
    networks:
      - backend
    environment:
      - TZ=Europe/Rome
    restart: always
    depends_on:
      - db
      - zookeeper
      - kafka

  producerstats:
    image: statea/producerstats
    platform: linux/amd64
    build: ./producerstats/
    hostname: producerstats
    networks:
      - backend
    environment:
      - TZ=Europe/Rome
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - redis

  consumerforecasts:
    image: statea/consumerforecasts
    platform: linux/amd64
    build: ./consumerforecasts/
    hostname: consumerforecasts
    networks:
      - backend
    environment:
      - TZ=Europe/Rome
    restart: always
    depends_on:
      - db
      - zookeeper
      - kafka

  producerforecasts:
    image: statea/producerforecasts
    platform: linux/amd64
    build: ./producerforecasts/
    hostname: producerforecasts
    networks:
      - backend
    environment:
      - TZ=Europe/Rome
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - redis

  db:
    image: mariadb:jammy
    platform: linux/amd64
    hostname: db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MARIADB_ROOT_PASSWORD=test
    restart: always

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    platform: linux/amd64
    hostname: zookeeper
    networks:
      - backend
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
      - ZOO_ENABLE_AUTH=yes
      # user that kafka brokers will use to connect to zookeeper
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=UkBCKB7qN2Fk3t.W
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=UkBCKB7qN2Fk3t.W
      # Heap memory size
      - ZOO_HEAP_SIZE=256
    volumes:
      - zookeeper-data:/bitnami/zookeeper/data
    restart: always

  kafka:
    image: statea/kafka
    platform: linux/amd64
    build: ./kafka/
    hostname: kafka
    networks:
      - backend
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=UkBCKB7qN2Fk3t.W
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_TLS_CLIENT_AUTH=required
      - KAFKA_CFG_SSL_KEYSTORE_FILENAME=kafka.server.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=mimimmi
      - KAFKA_CFG_SSL_KEY_PASSWORD=mimimmi
      - KAFKA_CFG_SSL_TRUSTSTORE_FILENAME=kafka.server.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=mimimmi
      - KAFKA_CFG_LOG4J_ROOT_LOGLEVEL=DEBUG
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      # sets unlimited retention of topic messages
      - KAFKA_CFG_LOG_RETENTION_BYTES=-1
      - KAFKA_CFG_LOG_RETENTION_MS=-1
      # Heap memory size
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms128m
    volumes:
      - kafka-data:/bitnami/kafka/data
    restart: always
    depends_on:
      - zookeeper

  redis:
    image: statea/redis
    platform: linux/amd64
    build: ./myredis/
    hostname: redis
    networks:
      - backend
    volumes:
      - redis-data:/data
    restart: always

  fintech:
    image: statea/fintech
    platform: linux/amd64
    build: ./fintech/
    hostname: fintech
    networks:
      - backend
    restart: always
    depends_on:
      - db

volumes:
  db-data:
  zookeeper-data:
  kafka-data:
  redis-data:

networks:
  frontend: {}
  backend: {}